name: hello_flutter
description: a social recipe app to keep track of new dishes, and share with friends.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  firebase_auth: ^3.1.3
  cloud_firestore: ^2.5.3
  firebase_core: ^1.7.0
  flutter:
    sdk: flutter
  flutter_lints: ^1.0.4
  google_fonts: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/food_pics/
    - assets/magazine_pics/
    - assets/sample_data/
    - assets/profile_pics/
